# -*- coding: utf-8 -*-
"""
Nuclio handler for CVAT yolov12n detection.

Auto-generated by generate_nuclio_function.py
"""

import json
import base64
import io
import requests
from PIL import Image


def handler(context, event):
    """
    Handle CVAT detection request.

    Args:
        context: Nuclio context object.
        event: Nuclio event containing the image data.

    Returns:
        Response with detection results in CVAT format.
    """
    context.logger.info("Run yolov12n model")

    data = event.body
    buf = io.BytesIO(base64.b64decode(data["image"]))
    image = Image.open(buf)

    # Convert to RGB if necessary
    if image.mode != "RGB":
        image = image.convert("RGB")

    # Encode image to base64
    buffered = io.BytesIO()
    image.save(buffered, format="JPEG")
    img_str = base64.b64encode(buffered.getvalue()).decode('utf-8')

    # FastAPI endpoint URL
    fastapi_url = "http://172.21.131.139:5001/infer"

    try:
        # Prepare and send request
        payload = {"image_base64": img_str}
        response = requests.post(fastapi_url, json=payload, timeout=25)
        response.raise_for_status()

        # Return FastAPI response directly
        return context.Response(
            body=response.text,
            headers={},
            content_type='application/json',
            status_code=200
        )

    except requests.exceptions.RequestException as e:
        context.logger.error(f"Error communicating with FastAPI service: {e}")
        return context.Response(
            body=json.dumps({"error": str(e)}),
            headers={},
            content_type='application/json',
            status_code=500
        )
    except Exception as e:
        context.logger.error(f"Error processing request: {e}")
        return context.Response(
            body=json.dumps({"error": str(e)}),
            headers={},
            content_type='application/json',
            status_code=500
        )
